### ISSUE TITLE
Package shows in Package Control in Windows but not Linux

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Gopinath001/CPrettify-Sublime-text-3#15]
Strangely, the following occurs. On Sublime build 4129, Windows 10, using Package Control, I can find and install the package. On the same build of Sublime, but on Linux Mint, Package Control cannot find the package.

**Comment by aghontpi** [comment]
Sorry for the late reply.

Yes, this only supports windows, [its configured that way](https://github.com/wbond/package_control_channel/blob/f63fd2b632e7e25c66f1e0135c14e13cd3917772/repository/c.json#L3870-L3880).

I had plans to extend this for `linux` and `mac`, but shortly after this project I stopped using sublime and switched to `vim` & `vscode`.
